FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared /app/shared
COPY services/order-service /app/services/order-service
EXPOSE 8002
CMD ["python", "services/order-service/app.py"]
