FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared /app/shared
COPY services/inventory-service /app/services/inventory-service
EXPOSE 8003
CMD ["python", "services/inventory-service/app.py"]
