FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared /app/shared
COPY services/payment-service /app/services/payment-service
EXPOSE 8004
CMD ["python", "services/payment-service/app.py"]
