FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared /app/shared
COPY services/notification-service /app/services/notification-service
EXPOSE 8005
CMD ["python", "services/notification-service/app.py"]
